// Code generated by go2go; DO NOT EDIT.


//line parallel_stream.go2:1
package stream

//line parallel_stream.go2:1
import (
//line parallel_stream.go2:1
 "sort"
//line parallel_stream.go2:1
 "testing"
//line parallel_stream.go2:1
)

//line parallel_stream.go2:1
type Importable୦ int
//line parallel_stream.go2:1
type _ sort.Float64Slice

//line parallel_stream.go2:1
var _ = testing.AllocsPerRun
