// Code generated by go2go; DO NOT EDIT.


//line stream.go2:1
package stream

//line stream.go2:1
import (
//line stream.go2:1
 "sort"
//line stream.go2:1
 "testing"
//line stream.go2:1
)

//line stream.go2:1
type Importable୦ int
//line stream.go2:1
type _ sort.Float64Slice

//line stream.go2:1
var _ = testing.AllocsPerRun
