#!/bin/sh
# Copyright 2021 gotomicro
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# To use, store as .git/hooks/pre-commit inside your repository and make sure
# it has execute permissions.
#
# This script does not handle file names that contain spaces.

# Pre-commit configuration

make check
printf "执行检查中...\n"

if [ $? -ne 0 ]; then
  echo >&2 "[ERROR]: 有文件发生变更，请将变更文件添加到本次提交中"
  exit 1
fi

exit 0