// Code generated by go2go; DO NOT EDIT.


//line ./pkg/collection/linkedlist_test.go2:1
package collection

//line ./pkg/collection/linkedlist_test.go2:1
import (
//line ./pkg/collection/linkedlist_test.go2:1
 "math/rand"
//line ./pkg/collection/linkedlist_test.go2:1
 "reflect"
//line ./pkg/collection/linkedlist_test.go2:1
 "testing"
//line ./pkg/collection/linkedlist_test.go2:1
 "time"
//line ./pkg/collection/linkedlist_test.go2:1
)

//line ./pkg/collection/linkedlist_test.go2:238
func TestLinkedListAPI(t *testing.T) {

	l := instantiate୦୦CreateLinkedList୦int()

	rand.Seed(time.Now().UnixNano())
	size := 10

	array := make([]int, size)

	for i := 0; i < size; i++ {
		array[i] = rand.Intn(10000)
	}

//line ./pkg/collection/linkedlist_test.go2:252
 for i := 0; i < 10; i++ {
		l.Append(array[i])
	}

	if l.Empty() {
		t.Fatalf("unexpected empty!")
	}

	if l.Len() != 10 {
		t.Fatalf("unexpected length!")
	}

	if l.Front() != array[0] {
		t.Fatalf("unexpected Front!")
	}

	if l.Back() != array[9] {
		t.Fatalf("unexpected Back!")
	}

//line ./pkg/collection/linkedlist_test.go2:273
 if !reflect.DeepEqual(l.Traverse(), array[:10]) {
		t.Fatalf("unexpected Traverse!")
	}

//line ./pkg/collection/linkedlist_test.go2:278
 l.Set(1050, 0)
	if l.Front() != 1050 {
		t.Fatalf("unexpected Set!")
	}

	l.Set(1050, -1)
	if l.Back() != 1050 {
		t.Fatalf("unexpected Set!")
	}

	if val, ok := l.Get(0); ok && val != 1050 {
		t.Fatalf("unexpected Get!")
	}

	if val, ok := l.Get(-1); ok && val != 1050 {
		t.Fatalf("unexpected Get!")
	}

//line ./pkg/collection/linkedlist_test.go2:297
 l.Remove(-1)
	if l.Len() != 9 {
		t.Fatalf("unexpected Remove!")
	}

//line ./pkg/collection/linkedlist_test.go2:303
 l.Add(1232, 3)
	if l.Len() != 10 {
		t.Fatalf("unexpected Add!")
	}

	if val, ok := l.Get(3); ok && val != 1232 {
		t.Fatalf("unexpected Get!")
	}

//line ./pkg/collection/linkedlist_test.go2:313
 l.Clear()
	if !l.Empty() {
		t.Fatalf("unexpected Clear!")
	}
}
//line ./pkg/collection/linkedlist_test.go2:26
func instantiate୦୦CreateLinkedList୦int() *instantiate୦୦linkedList୦int {
	h, t := &instantiate୦୦linkedListNode୦int{}, &instantiate୦୦linkedListNode୦int{}
	h.Prev, h.Next, t.Prev, t.Next = t, t, h, h
	return &instantiate୦୦linkedList୦int{
		h,
		t,
		0,
	}
}

//line ./pkg/collection/linkedlist_test.go2:34
type instantiate୦୦linkedList୦int struct {
//line ./pkg/collection/linkedlist_test.go2:21
 head, tail *instantiate୦୦linkedListNode୦int

						len int
}

//line ./pkg/collection/linkedlist_test.go2:36
func (l *instantiate୦୦linkedList୦int,) Len() int {
	return l.len
}

func (l *instantiate୦୦linkedList୦int,) Empty() bool {
	return l.len == 0
}

func (l *instantiate୦୦linkedList୦int,) Clear() {
	l.len = 0
	l.head.Next, l.head.Prev, l.tail.Prev, l.tail.Next = l.tail, l.tail, l.head, l.head
}

func (l *instantiate୦୦linkedList୦int,) Traverse() []int {
	ret := make([]int, l.len)
	cur := l.head.Next
	for i := 0; i < l.Len(); i++ {
		ret[i], cur = cur.Val, cur.Next
	}
	return ret
}

//line ./pkg/collection/linkedlist_test.go2:65
func (l *instantiate୦୦linkedList୦int,) Add(val int, index int) {

	if index > l.len || index < -l.len-1 {
		return
	}

	if index >= 0 {
		l.addFromFirst(val, index)
	} else {
		l.addFromLast(val, -index)
	}

	l.len++
}

func (l *instantiate୦୦linkedList୦int,) addFromFirst(val int, index int) {
	cur := l.head
	for i := 0; i < index; i++ {
		cur = cur.Next
	}
	node := &instantiate୦୦linkedListNode୦int{
		Val: val,
	}
	node.Prev, node.Next, cur.Next, cur.Next.Prev = cur, cur.Next, node, node
}

func (l *instantiate୦୦linkedList୦int,) addFromLast(val int, index int) {
	cur := l.tail
	for i := 0; i < index; i++ {
		cur = cur.Prev
	}
	node := &instantiate୦୦linkedListNode୦int{
		Val: val,
	}
	node.Prev, node.Next, cur.Next, cur.Next.Prev = cur, cur.Next, node, node
}

//line ./pkg/collection/linkedlist_test.go2:109
func (l *instantiate୦୦linkedList୦int,) Set(val int, index int) {

	if l.Empty() || index >= l.len || index <= -l.len-1 {
		return
	}

	if index >= 0 {
		l.setFromFirst(val, index)
	} else {
		l.setFromLast(val, -index)
	}
}

func (l *instantiate୦୦linkedList୦int,) setFromFirst(val int, index int) {
	cur := l.head
	for i := 0; i < index; i++ {
		cur = cur.Next
	}
	cur.Next.Val = val
}

func (l *instantiate୦୦linkedList୦int,) setFromLast(val int, index int) {
	cur := l.tail
	for i := 0; i < index-1; i++ {
		cur = cur.Prev
	}
	cur.Prev.Val = val
}

//line ./pkg/collection/linkedlist_test.go2:145
func (l *instantiate୦୦linkedList୦int,) Remove(index int) {

	if l.Empty() || index >= l.len || index <= -l.len-1 {
		return
	}
	if index < 0 {
		l.removeFromLast(-index)
	} else {
		l.removeFromFirst(index)
	}
	l.len--
}

func (l *instantiate୦୦linkedList୦int,) removeFromLast(index int) {
	cur := l.tail
	for i := 0; i < index; i++ {
		cur = cur.Prev
	}
	cur.Prev, cur.Next, cur.Prev.Next, cur.Next.Prev = nil, nil, cur.Next, cur.Prev
}

func (l *instantiate୦୦linkedList୦int,) removeFromFirst(index int) {
	cur := l.head
	for i := 0; i < index+1; i++ {
		cur = cur.Next
	}
	cur.Prev, cur.Next, cur.Prev.Next, cur.Next.Prev = nil, nil, cur.Next, cur.Prev
}

//line ./pkg/collection/linkedlist_test.go2:175
func (l *instantiate୦୦linkedList୦int,) Append(val int) {
	node := &instantiate୦୦linkedListNode୦int{Val: val}
	l.tail.Prev.Next, l.tail.Prev, node.Prev, node.Next = node, node, l.tail.Prev, l.tail
	l.len++
}

//line ./pkg/collection/linkedlist_test.go2:183
func (l *instantiate୦୦linkedList୦int,) Front() (e int) {
	if !l.Empty() {
		return l.head.Next.Val
	}
	return
}

//line ./pkg/collection/linkedlist_test.go2:192
func (l *instantiate୦୦linkedList୦int,) Back() (e int) {
	if !l.Empty() {
		return l.tail.Prev.Val
	}
	return
}

//line ./pkg/collection/linkedlist_test.go2:207
func (l *instantiate୦୦linkedList୦int,) Get(index int) (val int, ok bool) {
	if l.Empty() || index >= l.len || index <= -l.len-1 {
		return
	}

	if index < 0 {
		val, ok = l.getFromLast(-index)
	} else {
		val, ok = l.getFromFirst(index)
	}
	return val, ok
}

func (l *instantiate୦୦linkedList୦int,) getFromFirst(index int) (

//line ./pkg/collection/linkedlist_test.go2:240
 int, bool) {
//line ./pkg/collection/linkedlist_test.go2:221
 cur := l.head.Next
							for i := 0; i < index; i++ {
		cur = cur.Next
	}
	return cur.Val, true
}

//line ./pkg/collection/linkedlist_test.go2:229
func (l *instantiate୦୦linkedList୦int,) getFromLast(index int) (

//line ./pkg/collection/linkedlist_test.go2:240
 int, bool) {
//line ./pkg/collection/linkedlist_test.go2:230
 cur := l.tail
							for i := 0; i < index; i++ {
		cur = cur.Prev
	}
	return cur.Val, true
}

//line ./pkg/collection/linkedlist_test.go2:235
type instantiate୦୦linkedListNode୦int struct {
//line ./pkg/collection/linkedlist_test.go2:14
 Val        int
						Prev, Next *instantiate୦୦linkedListNode୦int
}
//line ./pkg/collection/linkedlist_test.go2:16
type Importable୦ int

//line ./pkg/collection/linkedlist_test.go2:16
var _ = rand.ExpFloat64
//line ./pkg/collection/linkedlist_test.go2:16
var _ = reflect.Append
//line ./pkg/collection/linkedlist_test.go2:16
var _ = testing.AllocsPerRun

//line ./pkg/collection/linkedlist_test.go2:16
const _ = time.ANSIC
