// Code generated by go2go; DO NOT EDIT.


//line dao.go2:1
package dao

//line dao.go2:1
import (
//line dao.go2:1
 "context"
//line dao.go2:1
 "errors"
//line dao.go2:1
 "github.com/gotomicro/ego-kit/pkg/proxy"
//line dao.go2:1
 "reflect"
//line dao.go2:1
 "testing"
//line dao.go2:1
)

//line dao.go2:10
type User struct {
	Name   string
	Gender string
	Email  string
}

type UserDAO struct {
	Base        *instantiate୦୦BaseDAO୦dao୮aUser
	FindByEmail func(ctx context.Context, email string) (*User, error) `sql:"SELECT * FROM USER WHERE EMAIL = ?"`
}
//line dao.go2:19
type instantiate୦୦BaseDAO୦dao୮aUser struct {
//line dao.go2:22
 Insert func(ctx context.Context, t *User,

//line dao.go2:22
 ) (int64, error)
	Update func(ctx context.Context, t *User,

//line dao.go2:23
        cols ...string) (int64, error)
			Delete func(ctx context.Context, t *User,

//line dao.go2:24
 ) (int64, error)
			Find func(ctx context.Context, t *User,

//line dao.go2:25
 ) ([]*User,

//line dao.go2:25
         error)
			FindOne func(ctx context.Context, t *User,

//line dao.go2:26
 ) ([]*User,

//line dao.go2:26
     error)
			Get func(ctx context.Context, id int64) (*User,

//line dao.go2:27
  error)
}
//line dao.go2:28
type Importable୦ int

//line dao.go2:28
var _ = context.Background
//line dao.go2:28
var _ = errors.As

//line dao.go2:28
type _ proxy.Importable୦

//line dao.go2:28
var _ = reflect.Append
//line dao.go2:28
var _ = testing.AllocsPerRun
