// Code generated by go2go; DO NOT EDIT.


//line slice.go2:1
package slices

//line slice.go2:1
import (
//line slice.go2:1
 "fmt"
//line slice.go2:1
 "testing"
//line slice.go2:1
)

//line slice.go2:1
type Importable୦ int

//line slice.go2:1
var _ = fmt.Errorf
//line slice.go2:1
var _ = testing.AllocsPerRun
