// Code generated by go2go; DO NOT EDIT.


//line slice_test.go2:1
package slices

//line slice_test.go2:1
import (
//line slice_test.go2:1
 "fmt"
//line slice_test.go2:1
 "testing"
//line slice_test.go2:1
)

//line slice_test.go2:8
func TestDelete(t *testing.T) {
	values := []int{1, 2, 3, 4}
	values = instantiate୦୦Delete୦int(values, 1)
	fmt.Printf("%v", values)
}
//line slice.go2:3
func instantiate୦୦Delete୦int(values []int, index int) []int {
	if index < 0 || index > len(values)-1 {
		return values
	}
	if len(values) == 0 {
		return []int{}
	}
	res := make([]int, 0, len(values)-1)
	for i := range values {
		if i != index {
			res = append(res, values[i])
		}
	}
	return res
}

//line slice.go2:17
var _ = fmt.Errorf
//line slice.go2:17
var _ = testing.AllocsPerRun
