// Code generated by go2go; DO NOT EDIT.


//line demo_test.go2:1
package pkg

//line demo_test.go2:1
import "testing"

//line demo_test.go2:7
func TestHello(t *testing.T) {
	sum1 := instantiate୦୦Sum୦int32([]int32{0, 1, 2, 3})
	println(sum1)
	sum2 := instantiate୦୦Sum୦int64([]int64{0, 1, 2, 3, 4})
	println(sum2)
}

//line demo_test.go2:18
func instantiate୦୦Sum୦int32(values []int32,) int32 {
	var res int32
	for _, val := range values {
		res = res + val
	}
	return res
}
//line demo_test.go2:18
func instantiate୦୦Sum୦int64(values []int64,) int64 {
	var res int64
	for _, val := range values {
		res = res + val
	}
	return res
}

//line demo_test.go2:24
var _ = testing.AllocsPerRun
